apiVersion: v1
data:
  INSTANCES: {{.Values.sql.instance}}
kind: ConfigMap
metadata:
  name: nabu-psql-connection
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nabu.common.labels" . | indent 4 }}
