insert into public.chouette_info(id, prefix, referential, organisation, cuser, regtopp_version, regtopp_coordinate_projection, data_format,regtopp_calendar_strategy,enable_validation,migrate_data_to_provider) values (1, 'OST', 'ost', 'Rutebanken', 'admin@rutebanken.org', null, 'EPSG:32632','regtopp',null,true,21);
insert into public.chouette_info(id, prefix, referential, organisation, cuser, regtopp_version, regtopp_coordinate_projection, data_format,regtopp_calendar_strategy,enable_validation,migrate_data_to_provider) values (2, 'RUT', 'rut', 'Rutebanken', 'admin@rutebanken.org', null, 'EPSG:32632','regtopp',null,true,22);
insert into public.chouette_info(id, prefix, referential, organisation, cuser, regtopp_version, regtopp_coordinate_projection, data_format,regtopp_calendar_strategy,enable_validation,migrate_data_to_provider) values (3, 'HED', 'hed', 'Rutebanken', 'admin@rutebanken.org', null, 'EPSG:32632','regtopp',null,true,23);
insert into public.chouette_info(id, prefix, referential, organisation, cuser, regtopp_version, regtopp_coordinate_projection, data_format,regtopp_calendar_strategy,enable_validation,migrate_data_to_provider) values (4, 'OPP', 'opp', 'Rutebanken', 'admin@rutebanken.org', null, 'EPSG:32632','regtopp',null,true,24);
insert into public.chouette_info(id, prefix, referential, organisation, cuser, regtopp_version, regtopp_coordinate_projection, data_format,regtopp_calendar_strategy,enable_validation,migrate_data_to_provider) values (5, 'BRA', 'bra', 'Rutebanken', 'admin@rutebanken.org', null, 'EPSG:32632','regtopp',null,true,25);
insert into public.chouette_info(id, prefix, referential, organisation, cuser, regtopp_version, regtopp_coordinate_projection, data_format,regtopp_calendar_strategy,enable_validation,migrate_data_to_provider) values (6, 'VKT', 'vkt', 'Rutebanken', 'admin@rutebanken.org', null, 'EPSG:32632','regtopp',null,true,26);
insert into public.chouette_info(id, prefix, referential, organisation, cuser, regtopp_version, regtopp_coordinate_projection, data_format,regtopp_calendar_strategy,enable_validation,migrate_data_to_provider) values (7, 'AKT', 'akt', 'Rutebanken', 'admin@rutebanken.org', null, 'EPSG:32632','regtopp',null,true,27);
insert into public.chouette_info(id, prefix, referential, organisation, cuser, regtopp_version, regtopp_coordinate_projection, data_format,regtopp_calendar_strategy,enable_validation,migrate_data_to_provider) values (8, 'KOL', 'kol', 'Rutebanken', 'admin@rutebanken.org', null, 'EPSG:32632','regtopp',null,true,28);
insert into public.chouette_info(id, prefix, referential, organisation, cuser, regtopp_version, regtopp_coordinate_projection, data_format,regtopp_calendar_strategy,enable_validation,migrate_data_to_provider) values (9, 'HRD', 'hrd', 'Rutebanken', 'admin@rutebanken.org', null, null,'gtfs',null,false,29);
insert into public.chouette_info(id, prefix, referential, organisation, cuser, regtopp_version, regtopp_coordinate_projection, data_format,regtopp_calendar_strategy,enable_validation,migrate_data_to_provider) values (10, 'SOF', 'sof', 'Rutebanken', 'admin@rutebanken.org', null, 'EPSG:32632','regtopp',null,true,30);
insert into public.chouette_info(id, prefix, referential, organisation, cuser, regtopp_version, regtopp_coordinate_projection, data_format,regtopp_calendar_strategy,enable_validation,migrate_data_to_provider) values (11, 'MOR', 'mor', 'Rutebanken', 'admin@rutebanken.org', null, 'EPSG:32632','regtopp',null,true,31);
insert into public.chouette_info(id, prefix, referential, organisation, cuser, regtopp_version, regtopp_coordinate_projection, data_format,regtopp_calendar_strategy,enable_validation,migrate_data_to_provider) values (12, 'ATB', 'atb', 'Rutebanken', 'admin@rutebanken.org', null, 'EPSG:32632','regtopp',null,true,32);
insert into public.chouette_info(id, prefix, referential, organisation, cuser, regtopp_version, regtopp_coordinate_projection, data_format,regtopp_calendar_strategy,enable_validation,migrate_data_to_provider) values (13, 'NTR', 'ntr', 'Rutebanken', 'admin@rutebanken.org', null, 'EPSG:32632','regtopp',null,true,33);
insert into public.chouette_info(id, prefix, referential, organisation, cuser, regtopp_version, regtopp_coordinate_projection, data_format,regtopp_calendar_strategy,enable_validation,migrate_data_to_provider) values (14, 'NOR', 'nor', 'Rutebanken', 'admin@rutebanken.org', null, 'EPSG:4326','regtopp',null,true,34);  --THIS IS CORRECT
insert into public.chouette_info(id, prefix, referential, organisation, cuser, regtopp_version, regtopp_coordinate_projection, data_format,regtopp_calendar_strategy,enable_validation,migrate_data_to_provider) values (15, 'TRO', 'tro', 'Rutebanken', 'admin@rutebanken.org', null, 'EPSG:32633','regtopp',null,true,35);
insert into public.chouette_info(id, prefix, referential, organisation, cuser, regtopp_version, regtopp_coordinate_projection, data_format,regtopp_calendar_strategy,enable_validation,migrate_data_to_provider) values (16, 'FIN', 'fin', 'Rutebanken', 'admin@rutebanken.org', null, 'EPSG:32633','regtopp',null,true,36);
insert into public.chouette_info(id, prefix, referential, organisation, cuser, regtopp_version, regtopp_coordinate_projection, data_format,regtopp_calendar_strategy,enable_validation,migrate_data_to_provider) values (17, 'TOG', 'tog', 'Rutebanken', 'admin@rutebanken.org', null, 'EPSG:4326','regtopp',null,true,37); --THIS IS ALSO CORRECT
insert into public.chouette_info(id, prefix, referential, organisation, cuser, regtopp_version, regtopp_coordinate_projection, data_format,regtopp_calendar_strategy,enable_validation,migrate_data_to_provider) values (18, 'TEL', 'tel', 'Rutebanken', 'admin@rutebanken.org', null, 'EPSG:32632','regtopp',null,true,38);
insert into public.chouette_info(id, prefix, referential, organisation, cuser, regtopp_version, regtopp_coordinate_projection, data_format,regtopp_calendar_strategy,enable_validation,migrate_data_to_provider) values (19, 'NRI', 'nri', 'Rutebanken', 'admin@rutebanken.org', null, null,'gtfs',null,false,39);
insert into public.chouette_info(id, prefix, referential, organisation, cuser, regtopp_version, regtopp_coordinate_projection, data_format,regtopp_calendar_strategy,enable_validation,migrate_data_to_provider) values (20, 'NORWAY', 'norway', 'NOR-WAY Bussekspress AS', 'admin@rutebanken.org', null, null,'regtopp',null,true,40);

insert into public.chouette_info(id, prefix, referential, organisation, cuser, regtopp_version, regtopp_coordinate_projection, data_format,regtopp_calendar_strategy,enable_validation,migrate_data_to_provider) values (21, 'OST', 'rb_ost', 'Rutebanken', 'admin+ost@rutebanken.org', null, null,'neptune',null,false,null);
insert into public.chouette_info(id, prefix, referential, organisation, cuser, regtopp_version, regtopp_coordinate_projection, data_format,regtopp_calendar_strategy,enable_validation,migrate_data_to_provider) values (22, 'RUT', 'rb_rut', 'Rutebanken', 'admin+rut@rutebanken.org', null, null,'neptune',null,false,null);
insert into public.chouette_info(id, prefix, referential, organisation, cuser, regtopp_version, regtopp_coordinate_projection, data_format,regtopp_calendar_strategy,enable_validation,migrate_data_to_provider) values (23, 'HED', 'rb_hed', 'Rutebanken', 'admin+hed@rutebanken.org', null, null,'neptune',null,false,null);
insert into public.chouette_info(id, prefix, referential, organisation, cuser, regtopp_version, regtopp_coordinate_projection, data_format,regtopp_calendar_strategy,enable_validation,migrate_data_to_provider) values (24, 'OPP', 'rb_opp', 'Rutebanken', 'admin+opp@rutebanken.org', null, null,'neptune',null,false,null);
insert into public.chouette_info(id, prefix, referential, organisation, cuser, regtopp_version, regtopp_coordinate_projection, data_format,regtopp_calendar_strategy,enable_validation,migrate_data_to_provider) values (25, 'BRA', 'rb_bra', 'Rutebanken', 'admin+bra@rutebanken.org', null, null,'neptune',null,false,null);
insert into public.chouette_info(id, prefix, referential, organisation, cuser, regtopp_version, regtopp_coordinate_projection, data_format,regtopp_calendar_strategy,enable_validation,migrate_data_to_provider) values (26, 'VKT', 'rb_vkt', 'Rutebanken', 'adminvkt@rutebanken.org', null, null,'neptune',null,false,null);
insert into public.chouette_info(id, prefix, referential, organisation, cuser, regtopp_version, regtopp_coordinate_projection, data_format,regtopp_calendar_strategy,enable_validation,migrate_data_to_provider) values (27, 'AKT', 'rb_akt', 'Rutebanken', 'admin+akt@rutebanken.org', null, null,'neptune',null,false,null);
insert into public.chouette_info(id, prefix, referential, organisation, cuser, regtopp_version, regtopp_coordinate_projection, data_format,regtopp_calendar_strategy,enable_validation,migrate_data_to_provider) values (28, 'KOL', 'rb_kol', 'Rutebanken', 'admin+kol@rutebanken.org', null, null,'neptune',null,false,null);
insert into public.chouette_info(id, prefix, referential, organisation, cuser, regtopp_version, regtopp_coordinate_projection, data_format,regtopp_calendar_strategy,enable_validation,migrate_data_to_provider) values (29, 'HRD', 'rb_hrd', 'Rutebanken', 'admin+hrd@rutebanken.org', null, null,'neptune',null,false,null);
insert into public.chouette_info(id, prefix, referential, organisation, cuser, regtopp_version, regtopp_coordinate_projection, data_format,regtopp_calendar_strategy,enable_validation,migrate_data_to_provider) values (30, 'SOF', 'rb_sof', 'Rutebanken', 'admin+sof@rutebanken.org', null, null,'neptune',null,false,null);
insert into public.chouette_info(id, prefix, referential, organisation, cuser, regtopp_version, regtopp_coordinate_projection, data_format,regtopp_calendar_strategy,enable_validation,migrate_data_to_provider) values (31, 'MOR', 'rb_mor', 'Rutebanken', 'admin+mor@rutebanken.org', null, null,'neptune',null,false,null);
insert into public.chouette_info(id, prefix, referential, organisation, cuser, regtopp_version, regtopp_coordinate_projection, data_format,regtopp_calendar_strategy,enable_validation,migrate_data_to_provider) values (32, 'ATB', 'rb_atb', 'Rutebanken', 'admin+atb@rutebanken.org', null, null,'neptune',null,false,null);
insert into public.chouette_info(id, prefix, referential, organisation, cuser, regtopp_version, regtopp_coordinate_projection, data_format,regtopp_calendar_strategy,enable_validation,migrate_data_to_provider) values (33, 'NTR', 'rb_ntr', 'Rutebanken', 'admin+ntr@rutebanken.org', null, null,'neptune',null,false,null);
insert into public.chouette_info(id, prefix, referential, organisation, cuser, regtopp_version, regtopp_coordinate_projection, data_format,regtopp_calendar_strategy,enable_validation,migrate_data_to_provider) values (34, 'NOR', 'rb_nor', 'Rutebanken', 'admin+nor@rutebanken.org', null, null,'neptune',null,false,null);  --THIS IS CORRECT
insert into public.chouette_info(id, prefix, referential, organisation, cuser, regtopp_version, regtopp_coordinate_projection, data_format,regtopp_calendar_strategy,enable_validation,migrate_data_to_provider) values (35, 'TRO', 'rb_tro', 'Rutebanken', 'admin+tro@rutebanken.org', null, null,'neptune',null,false,null);
insert into public.chouette_info(id, prefix, referential, organisation, cuser, regtopp_version, regtopp_coordinate_projection, data_format,regtopp_calendar_strategy,enable_validation,migrate_data_to_provider) values (36, 'FIN', 'rb_fin', 'Rutebanken', 'admin+fin@rutebanken.org', null, null,'neptune',null,false,null);
insert into public.chouette_info(id, prefix, referential, organisation, cuser, regtopp_version, regtopp_coordinate_projection, data_format,regtopp_calendar_strategy,enable_validation,migrate_data_to_provider) values (37, 'TOG', 'rb_tog', 'Rutebanken', 'admin+tog@rutebanken.org', null, null,'neptune',null,false,null); --THIS IS ALSO CORRECT
insert into public.chouette_info(id, prefix, referential, organisation, cuser, regtopp_version, regtopp_coordinate_projection, data_format,regtopp_calendar_strategy,enable_validation,migrate_data_to_provider) values (38, 'TEL', 'rb_tel', 'Rutebanken', 'admin+tel@rutebanken.org', null, null,'neptune',null,false,null);
insert into public.chouette_info(id, prefix, referential, organisation, cuser, regtopp_version, regtopp_coordinate_projection, data_format,regtopp_calendar_strategy,enable_validation,migrate_data_to_provider) values (39, 'NRI', 'rb_nri', 'Rutebanken', 'admin+nri@rutebanken.org', null, null,'neptune',null,false,null);
insert into public.chouette_info(id, prefix, referential, organisation, cuser, regtopp_version, regtopp_coordinate_projection, data_format,regtopp_calendar_strategy,enable_validation,migrate_data_to_provider) values (40, 'NORWAY', 'rb_norway', 'Rutebanken', 'admin+norway@rutebanken.org', null, null,'neptune',null,false,null);


insert into public.provider(id, name, sftp_account, chouette_info_id) values (1, 'Østfold / Østfold Kollektivtrafikk', 'ostfold', 1);
insert into public.provider(id, name, sftp_account, chouette_info_id) values (2, 'Oslo og Akershus / Ruter', 'oslo-akershus', 2);
insert into public.provider(id, name, sftp_account, chouette_info_id) values (3, 'Hedmark / Hedmark-Trafikk', 'hedmark', 3);
insert into public.provider(id, name, sftp_account, chouette_info_id) values (4, 'Oppland / Opplandstrafikk', 'oppland', 4);
insert into public.provider(id, name, sftp_account, chouette_info_id) values (5, 'Buskerud / Brakar', 'buskerud', 5);
insert into public.provider(id, name, sftp_account, chouette_info_id) values (6, 'Vestfold / VkT', 'vestfold', 6);
insert into public.provider(id, name, sftp_account, chouette_info_id) values (7, 'Agder / AkT', 'agder', 7);
insert into public.provider(id, name, sftp_account, chouette_info_id) values (8, 'Rogaland / Kolumbus', 'rogaland', 8);
insert into public.provider(id, name, sftp_account, chouette_info_id) values (9, 'Hordaland / Skyss', 'hordaland', 9);
insert into public.provider(id, name, sftp_account, chouette_info_id) values (10, 'Sogn og Fjordane / Kringom', 'sogn-fjordane', 10);
insert into public.provider(id, name, sftp_account, chouette_info_id) values (11, 'Møre og Romsdal / Fram', 'more-romsdal', 11);
insert into public.provider(id, name, sftp_account, chouette_info_id) values (12, 'Sør-Trøndelag / AtB', 'sor-trondelag', 12);
insert into public.provider(id, name, sftp_account, chouette_info_id) values (13, 'Nord-Trøndelag', 'nord-trondelag', 13);
insert into public.provider(id, name, sftp_account, chouette_info_id) values (14, 'Nordland', 'nordland', 14);
insert into public.provider(id, name, sftp_account, chouette_info_id) values (15, 'Troms / Troms Fylkestrafikk', 'troms', 15);
insert into public.provider(id, name, sftp_account, chouette_info_id) values (16, 'Finnmark / Snelandia', 'finnmark', 16);
insert into public.provider(id, name, sftp_account, chouette_info_id) values (17, 'Tog / NSB', 'tog', 17);
insert into public.provider(id, name, sftp_account, chouette_info_id) values (18, 'Telemark', 'telemark', 18);
insert into public.provider(id, name, sftp_account, chouette_info_id) values (19, 'Norsk ReiseInformasjon', 'nri', 19);
insert into public.provider(id, name, sftp_account, chouette_info_id) values (20, 'NOR-WAY Bussekspress', 'norway', 20);

insert into public.provider(id, name, sftp_account, chouette_info_id) values (21, 'RB/Østfold / Østfold Kollektivtrafikk', null, 21);
insert into public.provider(id, name, sftp_account, chouette_info_id) values (22, 'RB/Oslo og Akershus / Ruter', null, 22);
insert into public.provider(id, name, sftp_account, chouette_info_id) values (23, 'RB/Hedmark / Hedmark-Trafikk', null, 23);
insert into public.provider(id, name, sftp_account, chouette_info_id) values (24, 'RB/Oppland / Opplandstrafikk', null,24);
insert into public.provider(id, name, sftp_account, chouette_info_id) values (25, 'RB/Buskerud / Brakar', null, 25);
insert into public.provider(id, name, sftp_account, chouette_info_id) values (26, 'RB/Vestfold / VkT', null, 26);
insert into public.provider(id, name, sftp_account, chouette_info_id) values (27, 'RB/Agder / AkT', null, 27);
insert into public.provider(id, name, sftp_account, chouette_info_id) values (28, 'RB/Rogaland / Kolumbus', null, 28);
insert into public.provider(id, name, sftp_account, chouette_info_id) values (29, 'RB/Hordaland / Skyss', null, 29);
insert into public.provider(id, name, sftp_account, chouette_info_id) values (30, 'RB/Sogn og Fjordane / Kringom', null, 30);
insert into public.provider(id, name, sftp_account, chouette_info_id) values (31, 'RB/Møre og Romsdal / Fram', null, 31);
insert into public.provider(id, name, sftp_account, chouette_info_id) values (32, 'RB/Sør-Trøndelag / AtB', null, 32);
insert into public.provider(id, name, sftp_account, chouette_info_id) values (33, 'RB/Nord-Trøndelag', null, 33);
insert into public.provider(id, name, sftp_account, chouette_info_id) values (34, 'RB/Nordland',null, 34);
insert into public.provider(id, name, sftp_account, chouette_info_id) values (35, 'RB/Troms / Troms Fylkestrafikk', null, 35);
insert into public.provider(id, name, sftp_account, chouette_info_id) values (36, 'RB/Finnmark / Snelandia', null, 36);
insert into public.provider(id, name, sftp_account, chouette_info_id) values (37, 'RB/Tog / NSB', null, 37);
insert into public.provider(id, name, sftp_account, chouette_info_id) values (38, 'RB/Telemark', null, 38);
insert into public.provider(id, name, sftp_account, chouette_info_id) values (39, 'RB/Norsk ReiseInformasjon', null, 39);
insert into public.provider(id, name, sftp_account, chouette_info_id) values (40, 'RB/NOR-WAY Bussekspress', null, 40);
