apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "nabu.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | indent 4 }}
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "nabu.name" . }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: '9001'
        prometheus.io/scrape: 'true'
      labels:
        {{- include "common.labels" . | indent 8 }}
    spec:
      containers:
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.17-alpine
          command:
            - /cloud_sql_proxy
            - -instances={{ .Values.sql.instance }}
            - -credential_file=/etc/nabu-service-account/credentials.json
            - -log_debug_stdout
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - sleep 30
          resources:
            requests:
              cpu: 50m
              memory: 40Mi
          volumeMounts:
            - mountPath: /etc/nabu-service-account
              name: nabu-service-account
        - name: nabu
          image: {{ .Values.image.identifier }}
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          env:
            - name: JAVA_OPTIONS
              value: -server -Xms{{ .Values.resources.xms }} -Xmx{{ .Values.resources.xmx }}
                -Dspring.config.location=/etc/application-config/application.properties
                -Dfile.encoding=UTF-8
            - name: TZ
              value: Europe/Oslo
            - name: SPRING_MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  key: nabu-smtp-username
                  name: ror-nabu-secret
            - name: SPRING_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: nabu-smtp-password
                  name: ror-nabu-secret
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: nabu-db-username
                  name: ror-nabu-secret
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: nabu-db-password
                  name: ror-nabu-secret
            - name: IAM_KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: nabu-keycloak-secret
                  name: ror-nabu-secret
          ports:
            - containerPort: {{ .Values.service.http.internalPort }}
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9001
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9001
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 5
          resources:
            limits:
              cpu: {{ .Values.resources.cpuLimit }}
              memory: {{ .Values.resources.memLimit }}
            requests:
              cpu: {{ .Values.resources.cpuRequest }}
              memory: {{ .Values.resources.memRequest }}
          volumeMounts:
            - mountPath: /etc/nabu-service-account
              name: nabu-service-account
            - mountPath: /etc/application-config
              name: application-config
              readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: nabu-service-account
          secret:
            defaultMode: 420
            secretName: ror-nabu-sa-key
        - name: application-config
          configMap:
            defaultMode: 420
            name: nabu-config