apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    traffic-type: api
    {{- include "common.labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: traefik
  name: timetable-admin-v1-events
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  {{- if eq .Values.env "production"}}
  - host: timetable-admin-v1-events-{{ .Release.Namespace }}.entur.io
  {{ else }}
  - host: timetable-admin-v1-events-{{ .Release.Namespace }}.{{ .Release.Namespace }}.entur.io
  {{- end}}
    http:
      paths:
        - pathType: ImplementationSpecific
          backend:
            service:
              name: {{ template "nabu.name" . }}
              port:
                number: {{ .Values.service.http.externalPort }}
