common:
  app: nabu
  shortname: nabu
  team: ror
  ingress:
    enabled: false
  service:
    externalPort: 80
    internalPort: 9004
  container:
    envFrom:
      - secretRef:
            name: nabu-psql-credentials
    labels: { customLogRetention: enabled }
    forceReplicas: 1
    image: ${artifact.metadata.image}
    cpu: 0.3
    memory: 1200
    cpuLimit: 1000m
    memoryLimit: 1800
    probes:
      liveness:
        path: /actuator/health/liveness
      readiness:
        path: /actuator/health/readiness
    prometheus:
      enabled: true
      path: /actuator/prometheus
    volumeMounts:
      - mountPath: /etc/application-config
        name: application-config
        readOnly: true
    volumes:
      - configMap:
          defaultMode: 420
          name: nabu-application
        name: application-config

  configmap:
    data:
      JDK_JAVA_OPTIONS:  -server -Xmx768m -Xms512m -Dspring.config.location=/etc/application-config/application.properties
        -Dfile.encoding=UTF-8
      TZ: Europe/Oslo
    enabled: true
    toEnv: true