common:
  env: tst
  replicas: 1

ingress:
  domainName: -gcp2.staging.entur.io

sql:
  instance: ent-nabu-tst:europe-west1:nabu-db-pg13

configMap:
  pubsubProjectId: entur-ror-test

  baba:
    service: http://baba.tst.entur.internal

  auth0:
    ror:
      url: https://ror-entur-staging.eu.auth0.com/
      audience: https://ror.api.staging.entur.io

  oauth2:
    client:
      id: QQQKCbhgPE1met2VDO8s9quG8U9Rb6q5
      url: https://ror-entur-staging.eu.auth0.com/oauth/token
      audience: https://ror.api.staging.entur.io
  mail:
    stopPlace: https://stoppested-stage.entur.org/
    routedb: https://rutedb.staging.entur.org/
    notificationFrom: varsel-stage@entur.org
    operator: https://operator-stage.entur.org/


