env: staging

sql:
  instance: entur-ror-test:europe-west1:nabu-db-1=tcp:5432

configMap:
  pubsubProjectId: entur-ror-test
  keycloakUrl: https://kc-stage.devstage.entur.io/auth
  mail:
    stopPlace: https://stoppested-stage.entur.org/
    routedb: https://rutedb.staging.entur.org/
    notificationFrom: varsel-stage@entur.org
    operator: https://operator-stage.entur.org/

ingress:
  loadBalancerIP: 130.211.80.129


