env: dev

sql:
  instance: entur-ror-dev:europe-west1:nabu-db-pg13=tcp:5432

configMap:
  pubsubProjectId:  entur-ror-dev

  baba:
    service: http://baba.dev.entur.internal

  auth0:
    ror:
      url: https://ror-entur-dev.eu.auth0.com/
      audience: https://ror.api.dev.entur.io

  oauth2:
    client:
      id: riGzFJDW8fmm2G3cHpNUlIjlhoAM8i03
      url: https://ror-entur-dev.eu.auth0.com/oauth/token
      audience: https://ror.api.dev.entur.io
  mail:
    stopPlace: https://stoppested-test.entur.org/
    routedb: https://rutedb.dev.entur.org/
    notificationFrom: varsel-test@entur.org
    operator: https://operator-test.entur.org/



