env: dev

replicas: 1


rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1
image:
  identifier: ${artifact.metadata.image}
  imagePullPolicy: Always
resources:
  cpuLimit: 600m
  memLimit: 1800Mi
  cpuRequest: 100m
  memRequest: 1200Mi
  xmx: 768m
  xms: 512m

service:
  http:
    externalPort: 80
    internalPort: 9004
