env: production

sql:
  instance: entur-ror-prod:europe-west1:nabu-db-1=tcp:5432

configMap:
  pubsubProjectId: entur-ror-prod
  keycloak:
    url:  https://auth.entur.org/auth
  auth0:
    ror:
      url: https://auth2.entur.org/
      audience: https://ror.api.entur.io

  oauth2:
    client:
      id: 681gbNw7L020V7xFZag37qOlDp1QtIrF
      url: https://auth2.entur.org/oauth/token
      audience: https://ror.api.entur.io
  mail:
    stopPlace: https://stoppested.entur.org/
    routedb: https://rutedb.entur.org/
    notificationFrom: varsel@entur.org
    operator: https://operator.entur.org/

ingress:
  loadBalancerIP: 35.205.233.237
