env: production

sql:
  instance: entur-ror-prod:europe-west1:nabu-db-1=tcp:5432

configMap:
  pubsubProjectId: entur-ror-prod
  keycloakUrl: https://auth.entur.org/auth
  mail:
    stopPlace: https://stoppested.entur.org/
    routedb: https://rutedb.entur.org/
    notificationFrom: varsel@entur.org
    operator: https://operator.entur.org/

ingress:
  loadBalancerIP: 35.205.233.237
