env: staging

sql:
  instance: radon-1287:europe-west1:nabu-db-1=tcp:5432

configMap:
  pubsubProjectId: radon-1287
  keycloakUrl: https://kc-stage.devstage.entur.io/auth
  mail:
    stopPlace: https://stoppested-stage.entur.org/
    routedb: https://rutedb.staging.entur.org/
    notificationFrom: varsel-stage@entur.org
    operator: https://operator-stage.entur.org/



