env: production

sql:
  instance: entur-ror-prod:europe-west1:nabu-db-1=tcp:5432

configMap:
  pubsubProjectId: entur-ror-prod
  keycloak:
    url:  https://auth.entur.org/auth
  auth0:
    ror:
      url: https://ror-entur.eu.auth0.com/
      audience: https://ror.api.entur.io

  oauth2:
    client:
      id: nabu
      url: https://auth.entur.org/auth/realms/rutebanken/protocol/openid-connect/token
      audience: account
  mail:
    stopPlace: https://stoppested.entur.org/
    routedb: https://rutedb.entur.org/
    notificationFrom: varsel@entur.org
    operator: https://operator.entur.org/

ingress:
  loadBalancerIP: 35.205.233.237
